spring.application.name=protospace-knt

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/protospace
spring.datasource.username=postgres
spring.datasource.password=eriko0422

spring.flyway.baselineOnMigrate=true