spring.application.name=protospace-knt

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/protospace
spring.datasource.username=postgres
spring.datasource.password=${POSTGRESQL_PASSWORD}

spring.flyway.baselineOnMigrate=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# 画像の保存先・読み込み先のディレクトリ指定
upload.path=uploads/